# Generated by Django 4.1 on 2023-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_products_product_image_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image_extra',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products/extra'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image_secundary',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products/secundary'),
        ),
    ]
