# Generated by Django 4.2 on 2023-04-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
