# Generated by Django 4.2 on 2023-04-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_alter_products_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
