# Generated by Django 4.2 on 2023-04-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
