# Generated by Django 4.2 on 2023-04-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_products_nombre_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='nombre_producto',
        ),
    ]
