# Generated by Django 4.2 on 2023-04-13 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0004_cart_item_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_item',
        ),
    ]
