# Generated by Django 4.2 on 2023-04-13 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0011_remove_products_nombre_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Carrito', '0005_delete_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrito.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
