# Generated by Django 4.1 on 2023-03-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='second_last_name',
        ),
    ]
