# Generated by Django 4.1 on 2023-03-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_rename_last_name_user_second_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
