# Generated by Django 4.2 on 2023-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
    ]
