# Generated by Django 4.2 on 2023-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_user_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
