# Generated by Django 4.2 on 2023-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='../TopChoice/static/img/perfil2.webp', upload_to='profile_img/'),
        ),
    ]
