# Generated by Django 4.2 on 2023-04-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0013_alter_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
