# Generated by Django 4.1 on 2023-03-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='first_last_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
