# Generated by Django 4.2 on 2023-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_compra', '0002_rename_last_name_order_first_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
