# Generated by Django 4.2 on 2023-04-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_compra', '0004_order_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='addres_2',
            new_name='address_2',
        ),
    ]
