# Generated by Django 4.2 on 2023-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_compra', '0005_rename_addres_1_order_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
