# Generated by Django 4.2 on 2023-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_compra', '0007_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
